### ISSUE TITLE
No PV data in live batches

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#95]
We see no (or very little PV data in the batches)

This might effect how the model is run, as when training, there are not empty fields

**Comment by peterdudfield** [comment]
Occasioanly do see results in the reight place, this might be when some PV data is available
<img width="398" alt="Screenshot 2022-05-19 at 13 30 16" src="https://user-images.githubusercontent.com/34686298/169293640-d90b72b7-679b-43e5-bfbe-cc3de4b250a2.png">

**Comment by JackKelly** [comment]
For `power_perceiver`, please can we turn off all interpolation? `power_perceiver` expects the "raw" (normalised) data, and it can handle PV data that's not at regular time intervals.

And, yeah, having some "old" PV data would be far preferable to having no PV data :slightly_smiling_face:  e.g. let's say we're creating a forecast at 10:00am. And there's no PV data for 9:30am - 10:00am (because PV data takes a while to flow through PVOutput.org). Then it'd be great to be able to give `power_perceiver` whatever PV data we have for 8:30am-9:30am.

(BTW, if neither PVOutput.org nor Passiv can give us timely PV data, then that feels like a strong argument to build our own data collection system as part of the SBRI project! Getting PV data within seconds of the hardware taking the reading might turn out to be quite important).

**Comment by peterdudfield** [comment]
We can those options in, intperolate=True
And yea this would be solved if we took a longer history of data. 

I think for this issue we should
1. Load 1.5 hours of pv history
2. interpolate up to now
3. only keep 30 mins of history

We should of course keep things flexible for `power_perciever` but I think right now, we should focus on getting resaonable outputs from CNN.

**Comment by JackKelly** [comment]
SGTM!

**Comment by peterdudfield** [comment]
Another thing we could do is search for some other active sites. This might be a bigger job fro training, but I think this CNN doesnt mind too much

**Comment by JackKelly** [comment]
> Another thing we could do is search for some other active sites.

Please remind me: When does the code currently update its list of "active" PV sites? (I think I remember suggesting that, for now, we should update the list manually?)

**Comment by peterdudfield** [comment]
https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fforecast$252F/log-events/streaming$252Fforecast$252Fe638bb46f6b9427a897a4cda7785249c$3Fstart$3D-60000

Deployed 1.0.16, but not seeing new bug

**Comment by peterdudfield** [comment]
Deployed 1.0.17, and there re plenty of pv examples now,

Need to check PV data is normalizes correectl now
